const gameOptions = {
  ROWS: 10,
  COLUMNS: 6,
  INTERVAL_SIZE: 4,
  BLOCK_WIDTH: 96,
  BLOCK_HEIGHT: 54,
  BLOCK_DARK_COLOR: '#fe494f',
  BLOCK_NORMAL_COLOR: '#fe755c',
  BLOCK_LIGHT_COLOR: '#f29e74',
  BALL_RADIUS: 10,
  BALL_SPEED: 10,
  BALL_SHOOT_TIMEOUT: 100,
  BALL_COLOR: '#5aa7f3',
  BONUS_RADIUS: 12,
  BONUS_COLOR: '#3ad361',
  AIM_COLOR: '#a7bed3',
  FIELD_COLOR: '#e5e5e5',
  SHADOW_COLOR: '#cccccc',
  MAX_RECORDS_COUNT: 20
};

export default gameOptions;
